### ISSUE TITLE
Warped body output

### ISSUE THREAD

**Issue by lichard49** [KyujinHan/Smplify-X-Perfect-Implementation#1]
Hi,

Thanks for your efforts on putting this together!

I am using the Colab and have managed to get it to run. However, the output that is generated is warped:

![image](https://github.com/user-attachments/assets/2289bc3a-267f-4d0a-9317-ddf18356e892)

Do you have any clue why that might be?

Thanks!

Richard

**Comment by KyujinHan** [comment]
Hello! Thank for your comment.

I dont know, why the result is strange...

Do you correctly download the model checkpoint?
Or, you may use the clear image (such that removing x, y axis of the image).
