### ISSUE TITLE
OpenPose service unavailable

### ISSUE THREAD

**Issue by liviubouruc** [KyujinHan/Smplify-X-Perfect-Implementation#4]
Hello!

When I try to install OpenPose, at the 3 wget s I get service unavailable:
![image](https://github.com/user-attachments/assets/bab48d7a-cb2b-404a-b1e7-9021dba566a6)

I think they may have changed something? Some weeks ago it worked.

The cell with OpenPose installation continues running and in the end it build the OpenPose, but when I try to run it, it doesn't work:

![image](https://github.com/user-attachments/assets/28d74afd-753e-4f52-b121-72036f227092)

Thanks!

**Comment by mobina-zibandehpoor** [comment]
I have the same problem as you; my code worked until last night, but today It doesn't work. I do not know what happened suddenly

**Comment by KyujinHan** [comment]
Thank you for comments!

When I checked this issue, the downlonad link is expired..
**But, I found a solution..!**

I will update the readme and colab code today, please check the readme.
Thank you!

**[New results]**
![image](https://github.com/user-attachments/assets/e03ce274-b560-4cb5-aa0f-c7fee7baa519)
![image](https://github.com/user-attachments/assets/eaea83e6-e8e8-4df0-8984-9c7b9997a516)

**Comment by KyujinHan** [comment]
I finished updating the code and readme..!
Please check and let me know🤗

Thank you!!

**Comment by mobina-zibandehpoor** [comment]
Thank you so much. The problem was solved, and the code ran the same as before.
